# Generated by Django 6.0.1 on 2026-01-18 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0004_alter_department_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("DEVICE", "Device"), ("MISC", "Miscellaneous")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_STOCK", "In Stock"),
                            ("ASSIGNED", "Assigned"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("DISPOSED", "Disposed"),
                            ("STOLEN", "Stolen"),
                        ],
                        default="IN_STOCK",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("USED", "Used"),
                            ("DAMAGED", "Damaged"),
                            ("BEYOND_REPAIR", "Beyond Repair"),
                        ],
                        default="USED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.station",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assetcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("DESKTOP", "Desktop"),
                            ("LAPTOP", "Laptop"),
                            ("TABLET", "Tablet"),
                            ("PRINTER", "Printer"),
                            ("STARLINK", "Starlink"),
                            ("SWITCH", "Switch"),
                            ("ROUTER", "Router"),
                            ("SMARTPHONE", "Smartphone"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("program", models.CharField(blank=True, max_length=100, null=True)),
                ("partner", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "partner_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("additional_notes", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MiscAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("additional_notes", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misc",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
    ]
