# Generated by Django 6.0.1 on 2026-01-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("locations", "0004_alter_department_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="current_station",
            field=models.ForeignKey(
                blank=True,
                help_text="Current physical location of the asset",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.station",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="asset",
            field=models.OneToOneField(
                limit_choices_to={"asset_type": "DEVICE"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device",
                to="assets.asset",
            ),
        ),
        migrations.AlterField(
            model_name="miscasset",
            name="asset",
            field=models.OneToOneField(
                limit_choices_to={"asset_type": "MISC"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="misc",
                to="assets.asset",
            ),
        ),
    ]
