# Generated by Django 6.0.1 on 2026-01-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_asset_current_station_alter_device_asset_and_more"),
        ("locations", "0004_alter_department_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetcategory",
            name="category_name",
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="name",
            field=models.CharField(default="", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[("DEVICE", "Device"), ("NON_DEVICE", "Non-Device Asset")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="condition",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("GOOD", "Good / Serviceable"),
                    ("FAIR", "Fair (Minor Issues)"),
                    ("DAMAGED", "Damaged"),
                    ("BEYOND_REPAIR", "Beyond Repair"),
                ],
                default="GOOD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="current_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.station",
            ),
        ),
        migrations.AlterField(
            model_name="assetcategory",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="device",
            name="additional_notes",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="device",
            name="partner_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_types",
                        to="assets.assetcategory",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="assets.devicetype"
            ),
        ),
        migrations.CreateModel(
            name="NonDeviceAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("quantity", models.PositiveIntegerField()),
                ("additional_notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.OneToOneField(
                        limit_choices_to={"asset_type": "NON_DEVICE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="non_device",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MiscAsset",
        ),
    ]
