# Generated by Django 6.0.1 on 2026-01-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "province_name",
                    models.CharField(
                        help_text="Enter the full name of the province (e.g., Harare).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "province_suffix",
                    models.CharField(
                        blank=True,
                        help_text="Enter unique province suffix (e.g., 01). National office = 00",
                        max_length=5,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district_name",
                    models.CharField(
                        help_text="Enter the full name of the district (e.g., Bulawayo Central).",
                        max_length=255,
                    ),
                ),
                (
                    "district_suffix",
                    models.CharField(
                        blank=True,
                        help_text="Enter unique district suffix (e.g., 01). District office = 00",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "district_code",
                    models.CharField(
                        help_text="Unique district code for administrative purposes.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        help_text="Select the province this district belongs to.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="locations.province",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=255)),
                ("station_address", models.CharField(max_length=255, unique=True)),
                (
                    "station_type",
                    models.CharField(
                        choices=[
                            ("HQ", "Headquarters Office"),
                            ("PO", "Provincial Office"),
                            ("DO", "District Office"),
                            ("FC", "Facility"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "station_suffix",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "station_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="locations.district",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="locations.province",
                    ),
                ),
            ],
        ),
    ]
