# Generated by Django 6.0.1 on 2026-01-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_department"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["department_name"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.RenameField(
            model_name="department",
            old_name="name",
            new_name="department_name",
        ),
    ]
